version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=P221
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mongodb
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_DATABASE=pharmacy
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=pharmacy
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
